---
apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    orgId: 1
    uid: oC9aIEdAs1
    url: http://localhost:9090
    basicAuth: true
    basicAuthUser: admin
    secureJsonData:
      basicAuthPassword: password
